### ISSUE TITLE
AttributeError: '_AppCtxGlobals' object has no attribute '_gds_metrics_start_time'

### ISSUE THREAD

**Issue by benvand** [alphagov/gds_metrics_python#4]
So I just had an interesting problem and thought I'd write it up in case it benefits anyone else.

http://github.com/alphagov/digitalmarketplace-*-frontend s are using `flask_wtf.csrf.CSRFProtect`
For example:

https://github.com/alphagov/digitalmarketplace-brief-responses-frontend/blob/9621f6da9fa05b33d9a7e34087050d76f3b75f58/app/__init__.py#L5

CSRF protect app initialisation adds a `before_request` that errors out and stops the request going any further.

In a test that raises a CSRF `ValidationError` we were experiencing a traceback like:
`py.test -k test_csrf_handler_redirects_to_login`
```
Traceback (most recent call last):
  File "digitalmarketplace-brief-responses-frontend/tests/app/test_application.py", line 99, in test_csrf_handler_redirects_to_login
    '/suppliers/opportunities/1/ask-a-question', data={'clarification_question': 'blah'},
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/test.py", line 840, in post
    return self.open(*args, **kw)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/testing.py", line 200, in open
    follow_redirects=follow_redirects
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/test.py", line 803, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/test.py", line 716, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/dmutils/request_id.py", line 151, in __call__
    return self.app(environ, rewrite_response_headers)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/dmutils/proxy_fix.py", line 13, in __call__
    return self.app(environ, start_response)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in finalize_request
    request_finished.send(self, response=response)
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/gds_metrics/__init__.py", line 83, in teardown_request
    resp_time = monotonic() - g._gds_metrics_start_time
  File "digitalmarketplace-brief-responses-frontend/venv/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: '_AppCtxGlobals' object has no attribute '_gds_metrics_start_time'
```

This was because `GDSMetrics.before_request` _wasn't_ being called.
But `GDSMetrics.teardown_request` was.

https://github.com/alphagov/gds_metrics_python/blob/e3609387d48cb6e7e17fd3482ab16484309fdde5/gds_metrics/__init__.py#L74

So the CSRF protect app initialisation adds a `before_request` that errors out and stops the request going any further. Which means `GDSMetrics.before_request` isn't run and `_gds_metrics_start_time` is never set.

To solve the problem we had to change the order of initialisation from 
```
csrf = CSRFProtect()
metrics = GDSMetrics()

csrf.init_app(application)
metrics.init_app(application)
```

to 

```
csrf = CSRFProtect()
metrics = GDSMetrics()

metrics.init_app(application)
csrf.init_app(application)

```

That way the metrics `before_request` is run before the csrf `before_request`

**Comment by leohemsted** [comment]
fixed for good by https://github.com/alphagov/gds_metrics_python/pull/8
